global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Monitoramento do backend Spring Boot
  - job_name: 'agentes-backend'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  # Monitoramento do Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitoramento do Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # Monitoramento do Keycloak
  - job_name: 'keycloak'
    static_configs:
      - targets: ['keycloak:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Monitoramento do Nginx (frontend)
  - job_name: 'nginx'
    static_configs:
      - targets: ['frontend:80']
    scrape_interval: 30s

