version: '3.8'
 
services:
  keycloak:
    build: .
    image: keycloak-agentes-voluntarios
    container_name: keycloak-agentes-voluntarios
    ports:
      - "8084:8080"  # HTTP (externa 8084 -> interna 8080)
    environment:
      - TZ=America/Sao_Paulo
      - LAN=pt_BR.UTF-8
      - LANGUAGE=pt_BR.UTF-8
      - LC_ALL=pt_BR.UTF-8
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    volumes:
      - ./.docker/dbdata2:/opt/jboss/keycloak/standalone/data
    entrypoint:
      - "/opt/jboss/tools/docker-entrypoint.sh"
      - "-Dkeycloak.profile=preview"
      - "-Dspi-theme-static-max-age=-1"
      - "-Dspi-theme-cache-themes=false"
      - "-Dspi-theme-cache-templates=false"
    command: >
      -Dorg.jboss.logging.provider=slf4j
      -Djboss.logging.level=DEBUG
      -Dorg.keycloak.email=DEBUG
 