FROM quay.io/keycloak/keycloak:12.0.4

ENV TZ='America/Sao_Paulo'  \
    LAN='pt_BR.UTF-8' \    
    LANGUAGE='pt_BR.UTF-8' \    
    LC_ALL='pt_BR.UTF-8'

ENTRYPOINT /opt/jboss/tools/docker-entrypoint.sh -Dkeycloak.profile=preview