-- Create missing sequence S_ANEXO_AUTO for ANEXO_AUTO_INFRACAO IDs (align with corrected DDL)
DECLARE
  v_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'S_ANEXO_AUTO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE S_ANEXO_AUTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;
END;
/

