-- Fix and realign foreign keys after ID column renames
-- Idempotent: drops if exists, recreates referencing new target columns

-- Helper to drop constraint if exists
-- (Use guarded blocks per constraint)

-- CREDENCIAL.ID_AGENTE -> AGENTE_VOLUNTARIO(ID)
BEGIN
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CREDENCIAL DROP CONSTRAINT FK_CRED_AGENTE'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CREDENCIAL DROP CONSTRAINT fk_cred_agente'; EXCEPTION WHEN OTHERS THEN NULL; END;
  EXECUTE IMMEDIATE 'ALTER TABLE CREDENCIAL ADD CONSTRAINT FK_CRED_AGENTE FOREIGN KEY (ID_AGENTE) REFERENCES AGENTE_VOLUNTARIO(ID)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- AGENTE_COMARCA -> AGENTE_VOLUNTARIO(ID) e COMARCA(ID)
BEGIN
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE AGENTE_COMARCA DROP CONSTRAINT FK_AC_AGENTE'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE AGENTE_COMARCA DROP CONSTRAINT fk_ac_agente'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE AGENTE_COMARCA DROP CONSTRAINT FK_AC_COMARCA'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE AGENTE_COMARCA DROP CONSTRAINT fk_ac_comarca'; EXCEPTION WHEN OTHERS THEN NULL; END;
  EXECUTE IMMEDIATE 'ALTER TABLE AGENTE_COMARCA ADD CONSTRAINT FK_AC_AGENTE FOREIGN KEY (AGENTE_ID) REFERENCES AGENTE_VOLUNTARIO(ID)';
  EXECUTE IMMEDIATE 'ALTER TABLE AGENTE_COMARCA ADD CONSTRAINT FK_AC_COMARCA FOREIGN KEY (COMARCA_ID) REFERENCES COMARCA(ID)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- AUTO_INFRACAO antigos FKs (agente/comarca) não são mais usados: remover para evitar inválidos
BEGIN
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE AUTO_INFRACAO DROP CONSTRAINT FK_AUTO_AGENTE'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE AUTO_INFRACAO DROP CONSTRAINT fk_auto_agente'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE AUTO_INFRACAO DROP CONSTRAINT FK_AUTO_COMARCA'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE AUTO_INFRACAO DROP CONSTRAINT fk_auto_comarca'; EXCEPTION WHEN OTHERS THEN NULL; END;
END;
/

